name: Testing runner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: run commands
      run: |
        pwd
        touch file.txt
        ls -l
